import{a as w,i as g,S as L}from"./assets/vendor-Sa4a0LJu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const S="49342840-003e2c292237fbf09de0074d9",M="https://pixabay.com/api/";async function m(t,r=1){var l,s;try{return(await w.get(M,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(e){throw new Error(((s=(l=e.response)==null?void 0:l.data)==null?void 0:s.message)||"Failed to fetch images")}}const p=t=>t.map(({webformatURL:r,largeImageURL:l,tags:s,likes:e,views:o,comments:c,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${r}" alt="${s}" width="360" />
        </a>
        <div class="thumb-block">
          <div class="block"><h2 class="title">Likes</h2><p class="amount">${e}</p></div>
          <div class="block"><h2 class="title">Views</h2><p class="amount">${o}</p></div>
          <div class="block"><h2 class="title">Comments</h2><p class="amount">${c}</p></div>
          <div class="block"><h2 class="title">Downloads</h2><p class="amount">${v}</p></div>
        </div>
      </li>`).join(""),q=document.querySelector(".form"),h=document.querySelector(".gallery"),E=document.querySelector(".loader"),y=document.querySelector("#load-more");document.querySelector(".container");let u="",a=1,d=0,f;function P(){f&&f.destroy(),f=new L(".gallery a",{captionsData:"alt",captionDelay:250})}function i(t){E.style.display=t?"block":"none"}function n(t){y.style.display=t?"block":"none"}function b(){g.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",timeout:5e3,close:!0,progressBar:!0})}function k(){const t=document.querySelector(".end-message");t&&t.remove()}async function $(t){if(t.preventDefault(),u=t.target.elements["search-text"].value.trim(),!!u){a=1,h.innerHTML="",n(!1),k(),i(!0);try{const r=await m(u,a);if(d=r.totalHits,r.hits.length===0){g.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"}),i(!1);return}h.innerHTML=p(r.hits),P(),i(!1),r.hits.length<15||a*15>=d?(n(!1),a*15>=d&&b()):n(!0)}catch(r){console.error(r),g.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),i(!1)}}}async function x(){a+=1,i(!0),n(!1);try{const t=await m(u,a);h.insertAdjacentHTML("beforeend",p(t.hits)),f.refresh(),i(!1);const{height:r}=h.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),t.hits.length<15||a*15>=d?(n(!1),b()):n(!0)}catch(t){console.error(t),g.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),i(!1)}}q.addEventListener("submit",$);y.addEventListener("click",x);n(!1);
//# sourceMappingURL=index.js.map
