import{a as v,S as L,i as g}from"./assets/vendor-Sa4a0LJu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const S="49342840-003e2c292237fbf09de0074d9",q="https://pixabay.com/api/";async function m(t,r=1){var s,i;try{return(await v.get(q,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(e){throw new Error(((i=(s=e.response)==null?void 0:s.data)==null?void 0:i.message)||"Failed to fetch images")}}const h=document.querySelector(".gallery");let a;const E=t=>t.map(({webformatURL:r,largeImageURL:s,tags:i,likes:e,views:o,comments:u,downloads:w})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${r}" alt="${i}" width="360" />
        </a>
        <div class="thumb-block">
          <div class="block"><h2 class="title">Likes</h2><p class="amount">${e}</p></div>
          <div class="block"><h2 class="title">Views</h2><p class="amount">${o}</p></div>
          <div class="block"><h2 class="title">Comments</h2><p class="amount">${u}</p></div>
          <div class="block"><h2 class="title">Downloads</h2><p class="amount">${w}</p></div>
        </div>
      </li>`).join("");function p(t,r=!1){const s=E(t);r?(h.insertAdjacentHTML("beforeend",s),a&&a.refresh()):(h.innerHTML=s,a&&a.destroy(),a=new L(".gallery a",{captionsData:"alt",captionDelay:250}))}function M(){h.innerHTML="",a&&(a.destroy(),a=null)}const P=document.querySelector(".form"),k=document.querySelector(".gallery"),$=document.querySelector(".loader"),y=document.querySelector("#load-more");document.querySelector(".container");let d="",l=1,f=0;function n(t){$.style.display=t?"block":"none"}function c(t){y.style.display=t?"block":"none"}function b(){g.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",timeout:5e3,close:!0,progressBar:!0})}async function B(t){if(t.preventDefault(),d=t.target.elements["search-text"].value.trim(),!!d){l=1,M(),c(!1),n(!0);try{const r=await m(d,l);if(f=r.totalHits,r.hits.length===0){g.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"}),n(!1);return}p(r.hits),n(!1),r.hits.length<15||l*15>=f?(c(!1),l*15>=f&&b()):c(!0)}catch{g.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),n(!1)}}}async function H(){l+=1,n(!0),c(!1);try{const t=await m(d,l);p(t.hits,!0),n(!1);const{height:r}=k.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),t.hits.length<15||l*15>=f?(c(!1),b()):c(!0)}catch{g.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),n(!1)}}P.addEventListener("submit",B);y.addEventListener("click",H);c(!1);
//# sourceMappingURL=index.js.map
